import type { Metadata } from "next";
import { Geist, Geist_Mono, Google_Sans_Code, Volkhov } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const geistSans = Volkhov({
  variable: "--font-volkov",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const sansCode = Google_Sans_Code({
  variable: "--font-sans-code",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "300", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${sansCode.variable} antialiased font-sans`}>
        <NuqsAdapter>{children}</NuqsAdapter>
        <Toaster richColors />
      </body>
    </html>
  );
}
